export { RiArrowUpSLine as ArrowUpIcon } from 'react-icons/ri'
export { RiArrowDownSLine as ArrowDownIcon } from 'react-icons/ri'
export { RiMoonLine as MoonIcon } from 'react-icons/ri'
export { RiSunLine as SunIcon } from 'react-icons/ri'
export { RiStickyNoteLine as NoteIcon } from 'react-icons/ri'
export { RiTaskLine as TaskIcon } from 'react-icons/ri'
export { RiDeleteBin7Line as DeleteIcon } from 'react-icons/ri'
export { RiCheckLine as Check } from 'react-icons/ri'
